export const TEMPLATES = [
  { id: 't01', title: 'Announce a new job role', category: 'linkedin', prompt: 'Write a LinkedIn post announcing that I just started a new role as [Job Title] at [Company]. Mention excitement and gratitude.' },
  { id: 't02', title: 'Share a career milestone', category: 'linkedin', prompt: 'Write a LinkedIn post celebrating [milestone, e.g. 5 years in tech / promotion to Senior Engineer] with a lesson learned.' },
  { id: 't03', title: 'Personal branding post', category: 'linkedin', prompt: 'Write a LinkedIn post that establishes my personal brand as a [role, e.g. full-stack developer] who specializes in [skill].' },
  { id: 't04', title: 'Open source project README', category: 'github-readme', prompt: 'Write a README.md for an open-source project called [Project Name] that does [short description]. Include installation and usage.' },
  { id: 't05', title: 'API library README', category: 'github-readme', prompt: 'Write a README for an API client library called [Library Name] for [service]. Include quick start code examples.' },
  { id: 't06', title: 'Hackathon project README', category: 'github-readme', prompt: 'Write a README for my hackathon project [Project Name], built with [tech stack], solving [problem].' },
  { id: 't07', title: 'Job application follow-up', category: 'email', prompt: 'Write a polite follow-up email after applying for the [Job Title] position at [Company] two weeks ago.' },
  { id: 't08', title: 'Client onboarding email', category: 'email', prompt: 'Write a welcoming onboarding email for a new client starting a project with my agency, [Agency Name].' },
  { id: 't09', title: 'Meeting request email', category: 'email', prompt: 'Write a professional email requesting a 30-minute meeting with [Name] to discuss [topic].' },
  { id: 't10', title: 'Software engineer resume bullet points', category: 'resume', prompt: 'Write 5 achievement-driven resume bullet points for a Software Engineer with experience in [tech stack, e.g. React, Node.js, PostgreSQL].' },
  { id: 't11', title: 'Career-switch resume summary', category: 'resume', prompt: 'Write a resume summary for someone switching careers from [old field] to [new field, e.g. software development].' },
  { id: 't12', title: 'Entry-level resume objective', category: 'resume', prompt: 'Write an entry-level resume objective for a recent graduate in [field] applying for [role].' },
  { id: 't13', title: 'Tailored cover letter', category: 'cover-letter', prompt: 'Write a cover letter for a [Job Title] position at [Company], highlighting my experience in [skills/experience].' },
  { id: 't14', title: 'Career-change cover letter', category: 'cover-letter', prompt: 'Write a cover letter explaining my transition from [old career] to [new career] for a role at [Company].' },
  { id: 't15', title: 'Internship cover letter', category: 'cover-letter', prompt: 'Write a cover letter for a [field] internship at [Company], emphasizing enthusiasm and relevant coursework.' },
  { id: 't16', title: 'Behavioral interview answer (STAR)', category: 'interview', prompt: 'Using the STAR method, help me craft an answer to: "Tell me about a time you faced a difficult challenge at work." My situation: [brief details].' },
  { id: 't17', title: 'Mock technical interview questions', category: 'interview', prompt: 'Generate 5 mock technical interview questions for a [role, e.g. Backend Developer] position focused on [technology].' },
  { id: 't18', title: '"Tell me about yourself" answer', category: 'interview', prompt: 'Help me write a strong 60-second "Tell me about yourself" answer for a [Job Title] interview. Background: [brief background].' },
  { id: 't19', title: 'REST API endpoint', category: 'programming', prompt: 'Write a REST API endpoint in [language/framework, e.g. Node.js Express] that handles [functionality, e.g. user login with JWT].' },
  { id: 't20', title: 'React custom hook', category: 'programming', prompt: 'Write a React custom hook that handles [functionality, e.g. debounced search input].' },
  { id: 't21', title: 'SQL query builder', category: 'programming', prompt: 'Write a SQL query that [describe the requirement, e.g. returns the top 5 customers by total order value].' },
  { id: 't22', title: 'Algorithm implementation', category: 'programming', prompt: 'Implement [algorithm name, e.g. binary search] in [language] with comments explaining each step.' },
  { id: 't23', title: 'Fix a runtime error', category: 'bug-fix', prompt: 'I am getting this error: [paste error message]. Here is my code: [paste code]. What is causing it and how do I fix it?' },
  { id: 't24', title: 'Fix a failing test', category: 'bug-fix', prompt: 'This test is failing: [paste test]. Here is the implementation: [paste code]. Help me identify and fix the bug.' },
  { id: 't25', title: 'Resolve a memory leak', category: 'bug-fix', prompt: 'My [language/framework] application appears to have a memory leak in this code: [paste code]. Help me find and fix it.' },
  { id: 't26', title: 'Walk through a stack trace', category: 'debug', prompt: 'Walk me through this stack trace and help me find the root cause: [paste stack trace].' },
  { id: 't27', title: 'Diagnose slow performance', category: 'debug', prompt: 'My [feature/function] is running slowly. Here is the code: [paste code]. Help me diagnose the bottleneck.' },
  { id: 't28', title: 'Debug unexpected output', category: 'debug', prompt: 'My function [function name] returns [unexpected output] instead of [expected output]. Code: [paste code].' },
  { id: 't29', title: 'Review a pull request', category: 'code-review', prompt: 'Review this code for readability, performance, and potential bugs: [paste code].' },
  { id: 't30', title: 'Security-focused code review', category: 'code-review', prompt: 'Review this code specifically for security vulnerabilities: [paste code].' },
  { id: 't31', title: 'Suggest refactor', category: 'code-review', prompt: 'Suggest a cleaner refactor for this function while preserving its behavior: [paste code].' },
  { id: 't32', title: 'API documentation', category: 'documentation', prompt: 'Write API documentation for this endpoint: [paste endpoint details, method, params, response].' },
  { id: 't33', title: 'Function docstring', category: 'documentation', prompt: 'Write a clear docstring/comment block for this function: [paste function].' },
  { id: 't34', title: 'Setup guide', category: 'documentation', prompt: 'Write a step-by-step setup guide for developers to run [Project Name] locally, using [tech stack].' },
  { id: 't35', title: 'Elevator pitch for a startup', category: 'startup-pitch', prompt: 'Write a 30-second elevator pitch for my startup, [Startup Name], which solves [problem] for [target audience].' },
  { id: 't36', title: 'Investor pitch outline', category: 'startup-pitch', prompt: 'Outline a 10-slide investor pitch deck for [Startup Name], a company building [product description].' },
  { id: 't37', title: 'Problem-solution statement', category: 'startup-pitch', prompt: 'Write a clear problem-solution statement for [Startup Name], targeting [target market].' },
  { id: 't38', title: 'Lean business plan', category: 'business-plan', prompt: 'Write a lean one-page business plan for [Business Idea], including target market, revenue model, and go-to-market strategy.' },
  { id: 't39', title: 'Competitive analysis', category: 'business-plan', prompt: 'Write a competitive analysis section comparing [My Business] to competitors [Competitor A] and [Competitor B].' },
  { id: 't40', title: 'Executive summary', category: 'business-plan', prompt: 'Write an executive summary for a business plan about [Business Idea].' },
  { id: 't41', title: 'Product launch copy', category: 'marketing-copy', prompt: 'Write marketing copy announcing the launch of [Product Name], a [product description], for [target audience].' },
  { id: 't42', title: 'Landing page headline + subtext', category: 'marketing-copy', prompt: 'Write 5 headline and subtext variations for a landing page selling [product/service].' },
  { id: 't43', title: 'Email newsletter promo', category: 'marketing-copy', prompt: 'Write a promotional email for [product/offer] with a clear call to action for [discount/deadline].' },
  { id: 't44', title: 'Product showcase caption', category: 'instagram', prompt: 'Write an Instagram caption showcasing [product/service] with an engaging hook and hashtags.' },
  { id: 't45', title: 'Behind-the-scenes caption', category: 'instagram', prompt: 'Write a behind-the-scenes Instagram caption about building [project/product].' },
  { id: 't46', title: 'Thread announcing a launch', category: 'twitter', prompt: 'Write a 5-tweet thread announcing the launch of [Product Name], explaining what it does and why it matters.' },
  { id: 't47', title: 'Hot take / opinion post', category: 'twitter', prompt: 'Write a punchy opinion post about [topic in tech/industry] designed to spark discussion.' },
  { id: 't48', title: 'Tutorial video script', category: 'youtube-script', prompt: 'Write a YouTube script teaching viewers how to [task, e.g. build a REST API with Express], including a strong hook and outro.' },
  { id: 't49', title: 'Product review script', category: 'youtube-script', prompt: 'Write a YouTube script reviewing [product/tool], covering pros, cons, and a final verdict.' },
  { id: 't50', title: 'How-it-works explainer script', category: 'youtube-script', prompt: 'Write a YouTube explainer script describing how [technology/concept] works for a beginner audience.' },
  { id: 't51', title: 'Deep-dive blog post', category: 'blog', prompt: 'Write a blog post explaining [topic] in depth, with practical examples, for an audience of [audience].' },
  { id: 't52', title: 'Listicle blog post', category: 'blog', prompt: 'Write a listicle blog post: "[Number] Ways to [achieve outcome]" for [target audience].' },
  { id: 't53', title: 'Paper summary', category: 'research-summary', prompt: 'Summarize the key findings, methodology, and implications of this research: [paste abstract or paper].' },
  { id: 't54', title: 'Topic literature overview', category: 'research-summary', prompt: 'Write a research summary of the current state of [topic], covering major findings and open questions.' },
  { id: 't55', title: 'Exam study notes', category: 'study-notes', prompt: 'Create structured study notes on [subject/topic] for an upcoming exam, with headings and key definitions.' },
  { id: 't56', title: 'Concept explained simply', category: 'study-notes', prompt: 'Explain [concept] in simple terms with an analogy, as if teaching a beginner.' },
  { id: 't57', title: 'Flashcard set', category: 'study-notes', prompt: 'Create a set of 10 question-and-answer flashcards on [topic].' },
  { id: 't58', title: 'General research question', category: 'general', prompt: 'Explain [topic] clearly, covering the key points a newcomer should understand.' },
  { id: 't59', title: 'Brainstorm ideas', category: 'general', prompt: 'Brainstorm 10 creative ideas for [goal, e.g. a hackathon project about sustainability].' },
  { id: 't60', title: 'Compare two options', category: 'general', prompt: 'Compare [Option A] and [Option B] across cost, performance, and ease of use, then recommend one for [use case].' },
]
